numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))
average = sum(numbers) / len(numbers)
print("Average:", average)
print("Largest number:", max(numbers))
print("Smallest number:", min(numbers))